import * as crypto from "node:crypto";
import * as esbuild from "esbuild";
import * as Effect from "effect/Effect";
import * as FileSystem from "effect/FileSystem";
import * as Path from "effect/Path";
import * as Schema from "effect/Schema";
import * as Provider from "alchemy/Provider";
import { Resource } from "alchemy/Resource";
import { version as convexVersion } from "convex";
import {
  AppDeclarationSchema,
  compileApp,
  type AppDeclaration,
  type FileMap,
} from "@alchemy/convex";
import { virtualFsPlugin } from "./Bundler/VirtualFsPlugin.ts";

export { AppDeclarationSchema } from "@alchemy/convex";

export const RuntimeFunctionMetadataSchema = Schema.Struct({
  path: Schema.String,
  kind: Schema.String,
});
export type RuntimeFunctionMetadata = Schema.Schema.Type<
  typeof RuntimeFunctionMetadataSchema
>;

export const RuntimeModuleConfigSchema = Schema.Struct({
  path: Schema.String,
  source: Schema.String,
  sourceMap: Schema.optionalKey(Schema.String),
  environment: Schema.Literals(["isolate", "node"]),
});
export type RuntimeModuleConfig = Schema.Schema.Type<
  typeof RuntimeModuleConfigSchema
>;

export const RuntimeModuleHashSchema = Schema.Struct({
  path: Schema.String,
  environment: Schema.Literals(["isolate", "node"]),
  sha256: Schema.String,
});
export type RuntimeModuleHash = Schema.Schema.Type<
  typeof RuntimeModuleHashSchema
>;

export const RuntimeNodeDependencySchema = Schema.Struct({
  name: Schema.String,
  version: Schema.String,
});
export type RuntimeNodeDependency = Schema.Schema.Type<
  typeof RuntimeNodeDependencySchema
>;

export const RuntimeComponentDefinitionSchema = Schema.Struct({
  definitionPath: Schema.String,
  definition: RuntimeModuleConfigSchema,
  dependencies: Schema.Array(Schema.String),
  schema: Schema.NullOr(RuntimeModuleConfigSchema),
  functions: Schema.Array(RuntimeModuleConfigSchema),
  udfServerVersion: Schema.String,
});
export type RuntimeComponentDefinition = Schema.Schema.Type<
  typeof RuntimeComponentDefinitionSchema
>;

export const RuntimeBundleSchema = Schema.Struct({
  files: Schema.ReadonlyMap(Schema.String, Schema.String),
  functionsDirectory: Schema.String,
  definition: Schema.NullOr(RuntimeModuleConfigSchema),
  definitionDependencies: Schema.Array(Schema.String),
  schema: Schema.NullOr(RuntimeModuleConfigSchema),
  modules: Schema.Array(RuntimeModuleConfigSchema),
  unchangedModuleHashes: Schema.Array(RuntimeModuleHashSchema),
  componentDefinitions: Schema.Array(RuntimeComponentDefinitionSchema),
  nodeDependencies: Schema.Array(RuntimeNodeDependencySchema),
  nodeVersion: Schema.optionalKey(Schema.String),
  forCodegen: Schema.optionalKey(Schema.Boolean),
  udfServerVersion: Schema.String,
  functionManifest: Schema.Array(RuntimeFunctionMetadataSchema),
  bundleHash: Schema.String,
  sizes: Schema.Struct({
    isolate: Schema.Number,
    node: Schema.Number,
    total: Schema.Number,
  }),
});
export type RuntimeBundle = Schema.Schema.Type<typeof RuntimeBundleSchema> & {
  readonly files: FileMap;
};

export const RuntimeAppDeclarationSchema = AppDeclarationSchema;

export interface AppBundleProps {
  readonly app: AppDeclaration;
  readonly projectRoot?: string;
  readonly generateSourceMaps?: boolean;
  readonly externalPackages?: ReadonlyArray<string>;
}

export const AppBundlePropsSchema = Schema.Struct({
  app: RuntimeAppDeclarationSchema,
  projectRoot: Schema.optionalKey(Schema.String),
  generateSourceMaps: Schema.optionalKey(Schema.Boolean),
  externalPackages: Schema.optionalKey(Schema.Array(Schema.String)),
});

export interface AppBundle extends Resource<
  "Convex.AppBundle",
  AppBundleProps,
  RuntimeBundle
> {}

export const AppBundle = Resource<AppBundle>("Convex.AppBundle");

const hashText = (input: string) =>
  Effect.sync(() => crypto.createHash("sha256").update(input).digest("hex"));

const convexUdfServerVersion = Effect.sync(
  () => process.env.CONVEX_VERSION_OVERRIDE ?? convexVersion,
);

const schemaPath = "convex/_alchemy/schema.ts";
const definitionPath = "convex/convex.config.ts";
const runtimePath = "convex/_alchemy/runtime.ts";
const generatedServerPath = "convex/_alchemy/_generated/server.ts";
const bundleOutdir = ".alchemy-convex-runtime-bundle";

const generatedServerSource = [
  "// Generated by @alchemy/convex-runtime.",
  'import { actionGeneric, httpActionGeneric, mutationGeneric, queryGeneric } from "convex/server";',
  "export const action = actionGeneric;",
  "export const httpAction = httpActionGeneric;",
  "export const mutation = mutationGeneric;",
  "export const query = queryGeneric;",
  "",
].join("\n");

export interface BundleFromAppOptions {
  readonly projectRoot?: string;
  readonly generateSourceMaps?: boolean;
  readonly externalPackages?: ReadonlyArray<string>;
}

interface RuntimeEntry {
  readonly path: string;
  readonly environment: RuntimeModuleConfig["environment"];
}

interface VirtualBundleOutput {
  readonly modules: ReadonlyArray<RuntimeModuleConfig>;
  readonly externalPackageNames: ReadonlySet<string>;
}

const definedBundleOptions = (options: BundleFromAppOptions) => ({
  ...(options.projectRoot === undefined
    ? {}
    : { projectRoot: options.projectRoot }),
  ...(options.generateSourceMaps === undefined
    ? {}
    : { generateSourceMaps: options.generateSourceMaps }),
  ...(options.externalPackages === undefined
    ? {}
    : { externalPackages: options.externalPackages }),
});

const moduleFromSource = (
  path: string,
  source: string,
): RuntimeModuleConfig => ({
  path,
  source,
  environment: "isolate",
});

const optionalModuleFromFiles = (files: FileMap, path: string) => {
  const source = files.get(path);
  return source === undefined ? null : moduleFromSource(path, source);
};

const withProjectRootModule = (
  path: Path.Path,
  app: AppDeclaration,
  projectRoot: string | undefined,
): AppDeclaration => {
  if (
    projectRoot === undefined ||
    app.module === undefined ||
    app.module.startsWith("file://") ||
    path.isAbsolute(app.module)
  ) {
    return app;
  }
  return {
    ...app,
    module: path.resolve(projectRoot, app.module),
  };
};

const withRuntimeGeneratedFiles = (files: FileMap): FileMap =>
  new Map([...files.entries(), [generatedServerPath, generatedServerSource]]);

const useNodeDirectiveSource =
  /^(?:\s|\/\/[^\r\n]*(?:\r?\n|$)|\/\*[\s\S]*?\*\/)*["']use node["'];?/;

const hasUseNodeDirective = (source: string | undefined) => {
  if (source === undefined || !source.includes("use node")) return false;
  return useNodeDirectiveSource.test(source);
};

const filePathFromFileUrl = (path: Path.Path, specifier: string) =>
  Effect.try({
    try: () => new URL(specifier),
    catch: (cause) => cause,
  }).pipe(
    Effect.flatMap((url) => path.fromFileUrl(url)),
    Effect.map((value): string | undefined => value),
    Effect.catch(() => Effect.succeed(undefined)),
  );

const modulePathFromSpecifier = (
  path: Path.Path,
  appModule: string | undefined,
  specifier: string,
) =>
  Effect.gen(function* () {
    if (specifier.startsWith("file://")) {
      return yield* filePathFromFileUrl(path, specifier);
    }
    if (path.isAbsolute(specifier)) return specifier;
    const appPath =
      appModule === undefined
        ? undefined
        : appModule.startsWith("file://")
          ? yield* filePathFromFileUrl(path, appModule)
          : path.isAbsolute(appModule)
            ? appModule
            : undefined;
    return appPath === undefined
      ? undefined
      : path.resolve(path.dirname(appPath), specifier);
  });

const inferGroupModuleUsesNode = (
  app: AppDeclaration,
  moduleSpecifier: string | undefined,
) =>
  Effect.gen(function* () {
    if (moduleSpecifier === undefined) return false;
    const fs = yield* FileSystem.FileSystem;
    const path = yield* Path.Path;
    const modulePath = yield* modulePathFromSpecifier(
      path,
      app.module,
      moduleSpecifier,
    );
    if (modulePath === undefined) return false;
    const exists = yield* fs
      .exists(modulePath)
      .pipe(Effect.catch(() => Effect.succeed(false)));
    if (!exists) return false;
    const source = yield* fs
      .readFileString(modulePath)
      .pipe(Effect.catch(() => Effect.succeed("")));
    return hasUseNodeDirective(source);
  });

const deployableEntriesFromApp = (
  app: AppDeclaration,
  files: FileMap,
  projectRoot: string | undefined,
) =>
  Effect.gen(function* () {
    const groupEntries = yield* Effect.forEach(
      Object.values(app.groups).filter(
        (group) => Object.keys(group.functions).length > 0,
      ),
      (group) =>
        Effect.gen(function* () {
          const path = `convex/_alchemy/${group.name}.ts`;
          const explicitEnvironment = hasUseNodeDirective(files.get(path))
            ? "node"
            : "isolate";
          const inferredNode =
            explicitEnvironment === "isolate" && projectRoot !== undefined
              ? yield* inferGroupModuleUsesNode(app, group.module)
              : false;
          return {
            path,
            environment: inferredNode ? "node" : explicitEnvironment,
          } satisfies RuntimeEntry;
        }),
    );
    return [
      ...groupEntries,
      ...(app.http
        ? [{ path: "convex/http.ts", environment: "isolate" as const }]
        : []),
    ].sort((left, right) => left.path.localeCompare(right.path));
  });

const outputPrefix = (projectRoot: string) =>
  `${projectRoot.replace(/\/$/, "")}/${bundleOutdir}/`;

const outputPathFromEsbuild = (projectRoot: string, outputPath: string) => {
  const prefix = outputPrefix(projectRoot);
  return outputPath.startsWith(prefix)
    ? outputPath.slice(prefix.length)
    : (outputPath.split(`${bundleOutdir}/`).at(-1) ?? outputPath);
};

const packageNameFromSpecifier = (specifier: string) => {
  if (
    specifier.startsWith(".") ||
    specifier.startsWith("/") ||
    specifier.startsWith("node:")
  ) {
    return undefined;
  }
  const parts = specifier.split("/");
  return specifier.startsWith("@") ? parts.slice(0, 2).join("/") : parts[0];
};

const externalPackageNamesFromMetafile = (
  metafile: esbuild.Metafile | undefined,
  externalPackages: ReadonlyArray<string>,
) => {
  const allowed = new Set(externalPackages);
  const names = new Set<string>();
  for (const output of Object.values(metafile?.outputs ?? {})) {
    for (const imported of output.imports) {
      if (imported.external !== true) continue;
      const name = packageNameFromSpecifier(imported.path);
      if (name === undefined) continue;
      if (allowed.has("*") || allowed.has(name)) names.add(name);
    }
  }
  return names;
};

const packageDirectoryFromName = (name: string) =>
  name.startsWith("@") ? name.split("/").slice(0, 2).join("/") : name;

const findPackageJson = (projectRoot: string, name: string) =>
  Effect.gen(function* () {
    const fs = yield* FileSystem.FileSystem;
    const path = yield* Path.Path;
    const packageDirectory = packageDirectoryFromName(name);
    let current = projectRoot;
    while (true) {
      const candidate = path.join(
        current,
        "node_modules",
        packageDirectory,
        "package.json",
      );
      const exists = yield* fs
        .exists(candidate)
        .pipe(Effect.catch(() => Effect.succeed(false)));
      if (exists) return candidate;
      const parent = path.dirname(current);
      if (parent === current) return undefined;
      current = parent;
    }
  });

const nodeDependencyForPackage = (projectRoot: string, name: string) =>
  Effect.gen(function* () {
    const fs = yield* FileSystem.FileSystem;
    const packageJson = yield* findPackageJson(projectRoot, name);
    if (packageJson === undefined) {
      return yield* Effect.fail(
        new Error(
          `External package "${name}" was bundled as a Node dependency, but no node_modules/${packageDirectoryFromName(name)}/package.json was found from ${projectRoot}.`,
        ),
      );
    }
    const raw = yield* fs.readFileString(packageJson);
    const version = yield* Effect.try({
      try: () => JSON.parse(raw).version,
      catch: (cause) => cause,
    });
    if (typeof version !== "string") {
      return yield* Effect.fail(
        new Error(
          `External package "${name}" was bundled as a Node dependency, but ${packageJson} does not declare a string version.`,
        ),
      );
    }
    return { name, version };
  });

const nodeDependenciesFromPackages = (
  projectRoot: string,
  names: ReadonlySet<string>,
) =>
  Effect.gen(function* () {
    const dependencies = yield* Effect.forEach(
      [...names].sort((left, right) => left.localeCompare(right)),
      (name) => nodeDependencyForPackage(projectRoot, name),
    );
    return dependencies.filter(
      (dependency): dependency is RuntimeNodeDependency =>
        dependency !== undefined,
    );
  });

const bundleVirtualEntryGroup = (
  files: FileMap,
  entries: ReadonlyArray<RuntimeEntry>,
  options: {
    readonly projectRoot: string;
    readonly generateSourceMaps: boolean;
    readonly externalPackages: ReadonlyArray<string>;
  },
  environment: RuntimeModuleConfig["environment"],
) =>
  Effect.tryPromise({
    try: async () => {
      if (entries.length === 0) {
        return {
          modules: [] as RuntimeModuleConfig[],
          externalPackageNames: new Set<string>(),
        };
      }
      const result = (await esbuild.build({
        absWorkingDir: options.projectRoot,
        bundle: true,
        entryNames: "[dir]/[name]",
        entryPoints: entries.map((entry) => entry.path),
        external: options.externalPackages.filter((name) => name !== "*"),
        format: "esm",
        logLevel: "silent",
        metafile: true,
        outbase: "convex",
        outdir: bundleOutdir,
        packages: options.externalPackages.includes("*")
          ? "external"
          : undefined,
        platform: environment === "node" ? "node" : "browser",
        plugins: [
          virtualFsPlugin({
            files,
            projectRoot: options.projectRoot,
          }) as esbuild.Plugin,
        ],
        sourcemap: options.generateSourceMaps ? "external" : false,
        target: "esnext",
        treeShaking: true,
        write: false,
      })) as esbuild.BuildResult & {
        outputFiles: esbuild.OutputFile[];
        metafile: esbuild.Metafile;
      };
      const sourceMaps = new Map(
        result.outputFiles
          .filter((file) => file.path.endsWith(".js.map"))
          .map((file) => [
            outputPathFromEsbuild(options.projectRoot, file.path).replace(
              /\.map$/,
              "",
            ),
            file.text,
          ]),
      );
      const modules = result.outputFiles
        .filter((file) => file.path.endsWith(".js"))
        .map((file) => {
          const path = outputPathFromEsbuild(options.projectRoot, file.path);
          return {
            path,
            source: file.text,
            ...(sourceMaps.has(path)
              ? { sourceMap: sourceMaps.get(path)! }
              : {}),
            environment,
          };
        })
        .sort((left, right) => left.path.localeCompare(right.path));
      return {
        modules,
        externalPackageNames: externalPackageNamesFromMetafile(
          result.metafile,
          options.externalPackages,
        ),
      };
    },
    catch: (cause) => cause,
  });

const bundleVirtualEntries = (
  files: FileMap,
  entries: ReadonlyArray<RuntimeEntry>,
  options: {
    readonly projectRoot: string;
    readonly generateSourceMaps: boolean;
    readonly externalPackages: ReadonlyArray<string>;
  },
) =>
  Effect.gen(function* () {
    const isolate = yield* bundleVirtualEntryGroup(
      files,
      entries.filter((entry) => entry.environment === "isolate"),
      options,
      "isolate",
    );
    const node = yield* bundleVirtualEntryGroup(
      files,
      entries.filter((entry) => entry.environment === "node"),
      options,
      "node",
    );
    return {
      modules: [...isolate.modules, ...node.modules].sort((left, right) =>
        left.path.localeCompare(right.path),
      ),
      externalPackageNames: new Set<string>([
        ...isolate.externalPackageNames,
        ...node.externalPackageNames,
      ]),
    } satisfies VirtualBundleOutput;
  });

const functionManifestFromApp = (app: AppDeclaration) =>
  [
    ...Object.values(app.groups).flatMap((group) =>
      Object.entries(group.functions).map(([name, declaration]) => ({
        path: `${group.name}:${name}`,
        kind: declaration.kind,
      })),
    ),
    ...Object.keys(app.http?.routes ?? {}).map((path) => ({
      path: `${app.http?.routes[path as `/${string}`]?.method ?? "GET"} ${path}`,
      kind: "http" as const,
    })),
  ].sort((left, right) => left.path.localeCompare(right.path));

export const bundleFromApp = (
  app: AppDeclaration,
  options: BundleFromAppOptions = {},
) =>
  Effect.gen(function* () {
    const decoded = yield* Schema.decodeUnknownEffect(AppBundlePropsSchema)({
      app,
      ...definedBundleOptions(options),
    });
    const decodedApp =
      decoded.projectRoot === undefined
        ? decoded.app
        : withProjectRootModule(
            yield* Path.Path,
            decoded.app,
            decoded.projectRoot,
          );
    const files = yield* Effect.try({
      try: () => compileApp(decodedApp),
      catch: (cause) => cause,
    });
    const entries = [...files.entries()].sort(([left], [right]) =>
      left.localeCompare(right),
    );
    const schema = optionalModuleFromFiles(files, schemaPath);
    const definition = optionalModuleFromFiles(files, definitionPath);
    const udfServerVersion = yield* convexUdfServerVersion;
    const deployableEntries = yield* deployableEntriesFromApp(
      decodedApp,
      files,
      decoded.projectRoot,
    );
    const entryPaths = new Set(deployableEntries.map((entry) => entry.path));
    const entryEnvironments = new Map(
      deployableEntries.map((entry) => [entry.path, entry.environment]),
    );
    const runtimeFiles = withRuntimeGeneratedFiles(files);
    const bundledModules =
      decoded.projectRoot === undefined
        ? undefined
        : yield* bundleVirtualEntries(runtimeFiles, deployableEntries, {
            projectRoot: decoded.projectRoot,
            generateSourceMaps: decoded.generateSourceMaps ?? false,
            externalPackages: decoded.externalPackages ?? [],
          });
    const bundledSchema =
      decoded.projectRoot === undefined || schema === null
        ? undefined
        : ((yield* bundleVirtualEntries(
            runtimeFiles,
            [{ path: schemaPath, environment: "isolate" }],
            {
              projectRoot: decoded.projectRoot,
              generateSourceMaps: decoded.generateSourceMaps ?? false,
              externalPackages: decoded.externalPackages ?? [],
            },
          )).modules[0] ?? null);
    const bundledDefinition =
      decoded.projectRoot === undefined || definition === null
        ? undefined
        : ((yield* bundleVirtualEntries(
            runtimeFiles,
            [{ path: definitionPath, environment: "isolate" }],
            {
              projectRoot: decoded.projectRoot,
              generateSourceMaps: decoded.generateSourceMaps ?? false,
              externalPackages: decoded.externalPackages ?? [],
            },
          )).modules[0] ?? null);
    const modules =
      bundledModules?.modules ??
      entries
        .filter(([path]) => entryPaths.has(path) && path !== runtimePath)
        .map(([path, source]) => ({
          path,
          source,
          environment: entryEnvironments.get(path) ?? "isolate",
        }));
    const nodeDependencies =
      decoded.projectRoot === undefined || bundledModules === undefined
        ? []
        : yield* nodeDependenciesFromPackages(
            decoded.projectRoot,
            bundledModules.externalPackageNames,
          );
    const finalSchema = bundledSchema ?? schema;
    const finalDefinition = bundledDefinition ?? definition;
    const sizedModules = [
      ...modules,
      ...(finalSchema ? [finalSchema] : []),
      ...(finalDefinition ? [finalDefinition] : []),
    ];
    const isolate = sizedModules
      .filter((module) => module.environment === "isolate")
      .reduce((sum, module) => sum + module.source.length, 0);
    const node = sizedModules
      .filter((module) => module.environment === "node")
      .reduce((sum, module) => sum + module.source.length, 0);
    const total = isolate + node;
    const bundleHash = yield* hashText(
      JSON.stringify({
        entries: entries.map(([path, source]) => [path, source]),
        definition: finalDefinition,
        modules,
        nodeDependencies,
        schema: finalSchema,
        udfServerVersion,
      }),
    );
    return {
      files,
      functionsDirectory: "convex",
      definition: finalDefinition,
      definitionDependencies: [],
      schema: finalSchema,
      modules,
      unchangedModuleHashes: [],
      componentDefinitions: [],
      nodeDependencies,
      udfServerVersion,
      functionManifest: functionManifestFromApp(decodedApp),
      bundleHash,
      sizes: {
        isolate,
        node,
        total,
      },
    };
  });

export const AppBundleProvider = () =>
  Provider.succeed(AppBundle, {
    stables: [],
    read: Effect.fn("Convex.AppBundle.read")(function* ({ output }) {
      return output;
    }),
    reconcile: Effect.fn("Convex.AppBundle.reconcile")(function* ({
      news,
      output,
    }) {
      const bundle = yield* bundleFromApp(news.app, definedBundleOptions(news));
      return output?.bundleHash === bundle.bundleHash ? output : bundle;
    }),
    delete: Effect.fn("Convex.AppBundle.delete")(function* () {
      return undefined;
    }),
  });
